// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Proto/applicant.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace HireFire.Grpc {
  public static partial class ApplicantService
  {
    static readonly string __ServiceName = "ApplicantService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::HireFire.Grpc.CreateApplicantRequest> __Marshaller_CreateApplicantRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::HireFire.Grpc.CreateApplicantRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::HireFire.Grpc.ApplicantResponse> __Marshaller_ApplicantResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::HireFire.Grpc.ApplicantResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::HireFire.Grpc.RemoveApplicantRequest> __Marshaller_RemoveApplicantRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::HireFire.Grpc.RemoveApplicantRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::HireFire.Grpc.RemoveApplicantResponse> __Marshaller_RemoveApplicantResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::HireFire.Grpc.RemoveApplicantResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::HireFire.Grpc.AddApplicantSkillRequest> __Marshaller_AddApplicantSkillRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::HireFire.Grpc.AddApplicantSkillRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::HireFire.Grpc.ApplicantSkillResponse> __Marshaller_ApplicantSkillResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::HireFire.Grpc.ApplicantSkillResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::HireFire.Grpc.GetApplicantSkillsRequest> __Marshaller_GetApplicantSkillsRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::HireFire.Grpc.GetApplicantSkillsRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::HireFire.Grpc.ApplicantSkillsResponse> __Marshaller_ApplicantSkillsResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::HireFire.Grpc.ApplicantSkillsResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::HireFire.Grpc.GetApplicantRequest> __Marshaller_GetApplicantRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::HireFire.Grpc.GetApplicantRequest.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::HireFire.Grpc.CreateApplicantRequest, global::HireFire.Grpc.ApplicantResponse> __Method_CreateApplicant = new grpc::Method<global::HireFire.Grpc.CreateApplicantRequest, global::HireFire.Grpc.ApplicantResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CreateApplicant",
        __Marshaller_CreateApplicantRequest,
        __Marshaller_ApplicantResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::HireFire.Grpc.RemoveApplicantRequest, global::HireFire.Grpc.RemoveApplicantResponse> __Method_RemoveApplicant = new grpc::Method<global::HireFire.Grpc.RemoveApplicantRequest, global::HireFire.Grpc.RemoveApplicantResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "RemoveApplicant",
        __Marshaller_RemoveApplicantRequest,
        __Marshaller_RemoveApplicantResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::HireFire.Grpc.AddApplicantSkillRequest, global::HireFire.Grpc.ApplicantSkillResponse> __Method_AddApplicantSkill = new grpc::Method<global::HireFire.Grpc.AddApplicantSkillRequest, global::HireFire.Grpc.ApplicantSkillResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "AddApplicantSkill",
        __Marshaller_AddApplicantSkillRequest,
        __Marshaller_ApplicantSkillResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::HireFire.Grpc.GetApplicantSkillsRequest, global::HireFire.Grpc.ApplicantSkillsResponse> __Method_GetApplicantSkills = new grpc::Method<global::HireFire.Grpc.GetApplicantSkillsRequest, global::HireFire.Grpc.ApplicantSkillsResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetApplicantSkills",
        __Marshaller_GetApplicantSkillsRequest,
        __Marshaller_ApplicantSkillsResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::HireFire.Grpc.GetApplicantRequest, global::HireFire.Grpc.ApplicantResponse> __Method_GetApplicantById = new grpc::Method<global::HireFire.Grpc.GetApplicantRequest, global::HireFire.Grpc.ApplicantResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetApplicantById",
        __Marshaller_GetApplicantRequest,
        __Marshaller_ApplicantResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::HireFire.Grpc.ApplicantReflection.Descriptor.Services[0]; }
    }

    /// <summary>Client for ApplicantService</summary>
    public partial class ApplicantServiceClient : grpc::ClientBase<ApplicantServiceClient>
    {
      /// <summary>Creates a new client for ApplicantService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public ApplicantServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for ApplicantService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public ApplicantServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected ApplicantServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected ApplicantServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::HireFire.Grpc.ApplicantResponse CreateApplicant(global::HireFire.Grpc.CreateApplicantRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateApplicant(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::HireFire.Grpc.ApplicantResponse CreateApplicant(global::HireFire.Grpc.CreateApplicantRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CreateApplicant, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::HireFire.Grpc.ApplicantResponse> CreateApplicantAsync(global::HireFire.Grpc.CreateApplicantRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateApplicantAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::HireFire.Grpc.ApplicantResponse> CreateApplicantAsync(global::HireFire.Grpc.CreateApplicantRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CreateApplicant, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::HireFire.Grpc.RemoveApplicantResponse RemoveApplicant(global::HireFire.Grpc.RemoveApplicantRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RemoveApplicant(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::HireFire.Grpc.RemoveApplicantResponse RemoveApplicant(global::HireFire.Grpc.RemoveApplicantRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_RemoveApplicant, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::HireFire.Grpc.RemoveApplicantResponse> RemoveApplicantAsync(global::HireFire.Grpc.RemoveApplicantRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RemoveApplicantAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::HireFire.Grpc.RemoveApplicantResponse> RemoveApplicantAsync(global::HireFire.Grpc.RemoveApplicantRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_RemoveApplicant, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::HireFire.Grpc.ApplicantSkillResponse AddApplicantSkill(global::HireFire.Grpc.AddApplicantSkillRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AddApplicantSkill(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::HireFire.Grpc.ApplicantSkillResponse AddApplicantSkill(global::HireFire.Grpc.AddApplicantSkillRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_AddApplicantSkill, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::HireFire.Grpc.ApplicantSkillResponse> AddApplicantSkillAsync(global::HireFire.Grpc.AddApplicantSkillRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AddApplicantSkillAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::HireFire.Grpc.ApplicantSkillResponse> AddApplicantSkillAsync(global::HireFire.Grpc.AddApplicantSkillRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_AddApplicantSkill, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::HireFire.Grpc.ApplicantSkillsResponse GetApplicantSkills(global::HireFire.Grpc.GetApplicantSkillsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetApplicantSkills(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::HireFire.Grpc.ApplicantSkillsResponse GetApplicantSkills(global::HireFire.Grpc.GetApplicantSkillsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetApplicantSkills, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::HireFire.Grpc.ApplicantSkillsResponse> GetApplicantSkillsAsync(global::HireFire.Grpc.GetApplicantSkillsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetApplicantSkillsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::HireFire.Grpc.ApplicantSkillsResponse> GetApplicantSkillsAsync(global::HireFire.Grpc.GetApplicantSkillsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetApplicantSkills, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::HireFire.Grpc.ApplicantResponse GetApplicantById(global::HireFire.Grpc.GetApplicantRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetApplicantById(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::HireFire.Grpc.ApplicantResponse GetApplicantById(global::HireFire.Grpc.GetApplicantRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetApplicantById, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::HireFire.Grpc.ApplicantResponse> GetApplicantByIdAsync(global::HireFire.Grpc.GetApplicantRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetApplicantByIdAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::HireFire.Grpc.ApplicantResponse> GetApplicantByIdAsync(global::HireFire.Grpc.GetApplicantRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetApplicantById, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override ApplicantServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new ApplicantServiceClient(configuration);
      }
    }

  }
}
#endregion
