// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Proto/application.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace HireFire.Grpc {

  /// <summary>Holder for reflection information generated from Proto/application.proto</summary>
  public static partial class ApplicationReflection {

    #region Descriptor
    /// <summary>File descriptor for Proto/application.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ApplicationReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChdQcm90by9hcHBsaWNhdGlvbi5wcm90byJAChhDcmVhdGVBcHBsaWNhdGlv",
            "blJlcXVlc3QSDgoGam9iX2lkGAEgASgDEhQKDGFwcGxpY2FudF9pZBgCIAEo",
            "AyKBAQoTQXBwbGljYXRpb25SZXNwb25zZRIKCgJpZBgBIAEoAxIOCgZqb2Jf",
            "aWQYAiABKAMSFAoMYXBwbGljYW50X2lkGAMgASgDEhQKDHN1Ym1pdHRlZF9h",
            "dBgEIAEoCRIiCgZzdGF0dXMYBSABKA4yEi5BcHBsaWNhdGlvblN0YXR1cypA",
            "ChFBcHBsaWNhdGlvblN0YXR1cxIQCgxVTkRFUl9SRVZJRVcQABIMCghERUNM",
            "SU5FRBABEgsKB01BVENIRUQQAjJaChJBcHBsaWNhdGlvblNlcnZpY2USRAoR",
            "Q3JlYXRlQXBwbGljYXRpb24SGS5DcmVhdGVBcHBsaWNhdGlvblJlcXVlc3Qa",
            "FC5BcHBsaWNhdGlvblJlc3BvbnNlQjgKJGNvbS5leGFtcGxlLmRhdGFiYXNl",
            "c2VydmVyLmdlbmVyYXRlZFABqgINSGlyZUZpcmUuR3JwY2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::HireFire.Grpc.ApplicationStatus), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::HireFire.Grpc.CreateApplicationRequest), global::HireFire.Grpc.CreateApplicationRequest.Parser, new[]{ "JobId", "ApplicantId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::HireFire.Grpc.ApplicationResponse), global::HireFire.Grpc.ApplicationResponse.Parser, new[]{ "Id", "JobId", "ApplicantId", "SubmittedAt", "Status" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum ApplicationStatus {
    [pbr::OriginalName("UNDER_REVIEW")] UnderReview = 0,
    [pbr::OriginalName("DECLINED")] Declined = 1,
    [pbr::OriginalName("MATCHED")] Matched = 2,
  }

  #endregion

  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class CreateApplicationRequest : pb::IMessage<CreateApplicationRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CreateApplicationRequest> _parser = new pb::MessageParser<CreateApplicationRequest>(() => new CreateApplicationRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CreateApplicationRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::HireFire.Grpc.ApplicationReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CreateApplicationRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CreateApplicationRequest(CreateApplicationRequest other) : this() {
      jobId_ = other.jobId_;
      applicantId_ = other.applicantId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CreateApplicationRequest Clone() {
      return new CreateApplicationRequest(this);
    }

    /// <summary>Field number for the "job_id" field.</summary>
    public const int JobIdFieldNumber = 1;
    private long jobId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long JobId {
      get { return jobId_; }
      set {
        jobId_ = value;
      }
    }

    /// <summary>Field number for the "applicant_id" field.</summary>
    public const int ApplicantIdFieldNumber = 2;
    private long applicantId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long ApplicantId {
      get { return applicantId_; }
      set {
        applicantId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CreateApplicationRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CreateApplicationRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (JobId != other.JobId) return false;
      if (ApplicantId != other.ApplicantId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (JobId != 0L) hash ^= JobId.GetHashCode();
      if (ApplicantId != 0L) hash ^= ApplicantId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (JobId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(JobId);
      }
      if (ApplicantId != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(ApplicantId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (JobId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(JobId);
      }
      if (ApplicantId != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(ApplicantId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (JobId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(JobId);
      }
      if (ApplicantId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ApplicantId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CreateApplicationRequest other) {
      if (other == null) {
        return;
      }
      if (other.JobId != 0L) {
        JobId = other.JobId;
      }
      if (other.ApplicantId != 0L) {
        ApplicantId = other.ApplicantId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            JobId = input.ReadInt64();
            break;
          }
          case 16: {
            ApplicantId = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            JobId = input.ReadInt64();
            break;
          }
          case 16: {
            ApplicantId = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ApplicationResponse : pb::IMessage<ApplicationResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ApplicationResponse> _parser = new pb::MessageParser<ApplicationResponse>(() => new ApplicationResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ApplicationResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::HireFire.Grpc.ApplicationReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ApplicationResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ApplicationResponse(ApplicationResponse other) : this() {
      id_ = other.id_;
      jobId_ = other.jobId_;
      applicantId_ = other.applicantId_;
      submittedAt_ = other.submittedAt_;
      status_ = other.status_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ApplicationResponse Clone() {
      return new ApplicationResponse(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private long id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "job_id" field.</summary>
    public const int JobIdFieldNumber = 2;
    private long jobId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long JobId {
      get { return jobId_; }
      set {
        jobId_ = value;
      }
    }

    /// <summary>Field number for the "applicant_id" field.</summary>
    public const int ApplicantIdFieldNumber = 3;
    private long applicantId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long ApplicantId {
      get { return applicantId_; }
      set {
        applicantId_ = value;
      }
    }

    /// <summary>Field number for the "submitted_at" field.</summary>
    public const int SubmittedAtFieldNumber = 4;
    private string submittedAt_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SubmittedAt {
      get { return submittedAt_; }
      set {
        submittedAt_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 5;
    private global::HireFire.Grpc.ApplicationStatus status_ = global::HireFire.Grpc.ApplicationStatus.UnderReview;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::HireFire.Grpc.ApplicationStatus Status {
      get { return status_; }
      set {
        status_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ApplicationResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ApplicationResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (JobId != other.JobId) return false;
      if (ApplicantId != other.ApplicantId) return false;
      if (SubmittedAt != other.SubmittedAt) return false;
      if (Status != other.Status) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0L) hash ^= Id.GetHashCode();
      if (JobId != 0L) hash ^= JobId.GetHashCode();
      if (ApplicantId != 0L) hash ^= ApplicantId.GetHashCode();
      if (SubmittedAt.Length != 0) hash ^= SubmittedAt.GetHashCode();
      if (Status != global::HireFire.Grpc.ApplicationStatus.UnderReview) hash ^= Status.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Id);
      }
      if (JobId != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(JobId);
      }
      if (ApplicantId != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(ApplicantId);
      }
      if (SubmittedAt.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(SubmittedAt);
      }
      if (Status != global::HireFire.Grpc.ApplicationStatus.UnderReview) {
        output.WriteRawTag(40);
        output.WriteEnum((int) Status);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Id);
      }
      if (JobId != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(JobId);
      }
      if (ApplicantId != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(ApplicantId);
      }
      if (SubmittedAt.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(SubmittedAt);
      }
      if (Status != global::HireFire.Grpc.ApplicationStatus.UnderReview) {
        output.WriteRawTag(40);
        output.WriteEnum((int) Status);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Id);
      }
      if (JobId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(JobId);
      }
      if (ApplicantId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ApplicantId);
      }
      if (SubmittedAt.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SubmittedAt);
      }
      if (Status != global::HireFire.Grpc.ApplicationStatus.UnderReview) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Status);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ApplicationResponse other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0L) {
        Id = other.Id;
      }
      if (other.JobId != 0L) {
        JobId = other.JobId;
      }
      if (other.ApplicantId != 0L) {
        ApplicantId = other.ApplicantId;
      }
      if (other.SubmittedAt.Length != 0) {
        SubmittedAt = other.SubmittedAt;
      }
      if (other.Status != global::HireFire.Grpc.ApplicationStatus.UnderReview) {
        Status = other.Status;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt64();
            break;
          }
          case 16: {
            JobId = input.ReadInt64();
            break;
          }
          case 24: {
            ApplicantId = input.ReadInt64();
            break;
          }
          case 34: {
            SubmittedAt = input.ReadString();
            break;
          }
          case 40: {
            Status = (global::HireFire.Grpc.ApplicationStatus) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt64();
            break;
          }
          case 16: {
            JobId = input.ReadInt64();
            break;
          }
          case 24: {
            ApplicantId = input.ReadInt64();
            break;
          }
          case 34: {
            SubmittedAt = input.ReadString();
            break;
          }
          case 40: {
            Status = (global::HireFire.Grpc.ApplicationStatus) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
