// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Proto/company.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace HireFire.Grpc {
  public static partial class CompanyService
  {
    static readonly string __ServiceName = "CompanyService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::HireFire.Grpc.CreateCompanyRequest> __Marshaller_CreateCompanyRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::HireFire.Grpc.CreateCompanyRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::HireFire.Grpc.CompanyResponse> __Marshaller_CompanyResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::HireFire.Grpc.CompanyResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::HireFire.Grpc.UpdateCompanyRequest> __Marshaller_UpdateCompanyRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::HireFire.Grpc.UpdateCompanyRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::HireFire.Grpc.GetCompaniesForRepresentativeRequest> __Marshaller_GetCompaniesForRepresentativeRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::HireFire.Grpc.GetCompaniesForRepresentativeRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::HireFire.Grpc.GetCompaniesForRepresentativeResponse> __Marshaller_GetCompaniesForRepresentativeResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::HireFire.Grpc.GetCompaniesForRepresentativeResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::HireFire.Grpc.GetCompaniesToApproveRequest> __Marshaller_GetCompaniesToApproveRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::HireFire.Grpc.GetCompaniesToApproveRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::HireFire.Grpc.GetCompaniesToApproveResponse> __Marshaller_GetCompaniesToApproveResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::HireFire.Grpc.GetCompaniesToApproveResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::HireFire.Grpc.ApproveCompanyRequest> __Marshaller_ApproveCompanyRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::HireFire.Grpc.ApproveCompanyRequest.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::HireFire.Grpc.CreateCompanyRequest, global::HireFire.Grpc.CompanyResponse> __Method_CreateCompany = new grpc::Method<global::HireFire.Grpc.CreateCompanyRequest, global::HireFire.Grpc.CompanyResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CreateCompany",
        __Marshaller_CreateCompanyRequest,
        __Marshaller_CompanyResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::HireFire.Grpc.UpdateCompanyRequest, global::HireFire.Grpc.CompanyResponse> __Method_UpdateCompany = new grpc::Method<global::HireFire.Grpc.UpdateCompanyRequest, global::HireFire.Grpc.CompanyResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "UpdateCompany",
        __Marshaller_UpdateCompanyRequest,
        __Marshaller_CompanyResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::HireFire.Grpc.GetCompaniesForRepresentativeRequest, global::HireFire.Grpc.GetCompaniesForRepresentativeResponse> __Method_GetCompaniesForRepresentative = new grpc::Method<global::HireFire.Grpc.GetCompaniesForRepresentativeRequest, global::HireFire.Grpc.GetCompaniesForRepresentativeResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetCompaniesForRepresentative",
        __Marshaller_GetCompaniesForRepresentativeRequest,
        __Marshaller_GetCompaniesForRepresentativeResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::HireFire.Grpc.GetCompaniesToApproveRequest, global::HireFire.Grpc.GetCompaniesToApproveResponse> __Method_GetCompaniesToApprove = new grpc::Method<global::HireFire.Grpc.GetCompaniesToApproveRequest, global::HireFire.Grpc.GetCompaniesToApproveResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetCompaniesToApprove",
        __Marshaller_GetCompaniesToApproveRequest,
        __Marshaller_GetCompaniesToApproveResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::HireFire.Grpc.ApproveCompanyRequest, global::HireFire.Grpc.CompanyResponse> __Method_ApproveCompany = new grpc::Method<global::HireFire.Grpc.ApproveCompanyRequest, global::HireFire.Grpc.CompanyResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ApproveCompany",
        __Marshaller_ApproveCompanyRequest,
        __Marshaller_CompanyResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::HireFire.Grpc.CompanyReflection.Descriptor.Services[0]; }
    }

    /// <summary>Client for CompanyService</summary>
    public partial class CompanyServiceClient : grpc::ClientBase<CompanyServiceClient>
    {
      /// <summary>Creates a new client for CompanyService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public CompanyServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for CompanyService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public CompanyServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected CompanyServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected CompanyServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::HireFire.Grpc.CompanyResponse CreateCompany(global::HireFire.Grpc.CreateCompanyRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateCompany(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::HireFire.Grpc.CompanyResponse CreateCompany(global::HireFire.Grpc.CreateCompanyRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CreateCompany, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::HireFire.Grpc.CompanyResponse> CreateCompanyAsync(global::HireFire.Grpc.CreateCompanyRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateCompanyAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::HireFire.Grpc.CompanyResponse> CreateCompanyAsync(global::HireFire.Grpc.CreateCompanyRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CreateCompany, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::HireFire.Grpc.CompanyResponse UpdateCompany(global::HireFire.Grpc.UpdateCompanyRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateCompany(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::HireFire.Grpc.CompanyResponse UpdateCompany(global::HireFire.Grpc.UpdateCompanyRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_UpdateCompany, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::HireFire.Grpc.CompanyResponse> UpdateCompanyAsync(global::HireFire.Grpc.UpdateCompanyRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateCompanyAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::HireFire.Grpc.CompanyResponse> UpdateCompanyAsync(global::HireFire.Grpc.UpdateCompanyRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_UpdateCompany, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::HireFire.Grpc.GetCompaniesForRepresentativeResponse GetCompaniesForRepresentative(global::HireFire.Grpc.GetCompaniesForRepresentativeRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetCompaniesForRepresentative(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::HireFire.Grpc.GetCompaniesForRepresentativeResponse GetCompaniesForRepresentative(global::HireFire.Grpc.GetCompaniesForRepresentativeRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetCompaniesForRepresentative, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::HireFire.Grpc.GetCompaniesForRepresentativeResponse> GetCompaniesForRepresentativeAsync(global::HireFire.Grpc.GetCompaniesForRepresentativeRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetCompaniesForRepresentativeAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::HireFire.Grpc.GetCompaniesForRepresentativeResponse> GetCompaniesForRepresentativeAsync(global::HireFire.Grpc.GetCompaniesForRepresentativeRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetCompaniesForRepresentative, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::HireFire.Grpc.GetCompaniesToApproveResponse GetCompaniesToApprove(global::HireFire.Grpc.GetCompaniesToApproveRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetCompaniesToApprove(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::HireFire.Grpc.GetCompaniesToApproveResponse GetCompaniesToApprove(global::HireFire.Grpc.GetCompaniesToApproveRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetCompaniesToApprove, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::HireFire.Grpc.GetCompaniesToApproveResponse> GetCompaniesToApproveAsync(global::HireFire.Grpc.GetCompaniesToApproveRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetCompaniesToApproveAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::HireFire.Grpc.GetCompaniesToApproveResponse> GetCompaniesToApproveAsync(global::HireFire.Grpc.GetCompaniesToApproveRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetCompaniesToApprove, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::HireFire.Grpc.CompanyResponse ApproveCompany(global::HireFire.Grpc.ApproveCompanyRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ApproveCompany(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::HireFire.Grpc.CompanyResponse ApproveCompany(global::HireFire.Grpc.ApproveCompanyRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ApproveCompany, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::HireFire.Grpc.CompanyResponse> ApproveCompanyAsync(global::HireFire.Grpc.ApproveCompanyRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ApproveCompanyAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::HireFire.Grpc.CompanyResponse> ApproveCompanyAsync(global::HireFire.Grpc.ApproveCompanyRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ApproveCompany, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override CompanyServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new CompanyServiceClient(configuration);
      }
    }

  }
}
#endregion
