// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Proto/job.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace HireFire.Grpc {
  public static partial class JobListingService
  {
    static readonly string __ServiceName = "JobListingService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::HireFire.Grpc.CreateJobListingRequest> __Marshaller_CreateJobListingRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::HireFire.Grpc.CreateJobListingRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::HireFire.Grpc.JobListingResponse> __Marshaller_JobListingResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::HireFire.Grpc.JobListingResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::HireFire.Grpc.GetJobListingsForCompanyRequest> __Marshaller_GetJobListingsForCompanyRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::HireFire.Grpc.GetJobListingsForCompanyRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::HireFire.Grpc.GetJobListingsForCompanyResponse> __Marshaller_GetJobListingsForCompanyResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::HireFire.Grpc.GetJobListingsForCompanyResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::HireFire.Grpc.GetJobListingsForRecruiterRequest> __Marshaller_GetJobListingsForRecruiterRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::HireFire.Grpc.GetJobListingsForRecruiterRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::HireFire.Grpc.GetJobListingsForRecruiterResponse> __Marshaller_GetJobListingsForRecruiterResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::HireFire.Grpc.GetJobListingsForRecruiterResponse.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::HireFire.Grpc.CreateJobListingRequest, global::HireFire.Grpc.JobListingResponse> __Method_CreateJobListing = new grpc::Method<global::HireFire.Grpc.CreateJobListingRequest, global::HireFire.Grpc.JobListingResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CreateJobListing",
        __Marshaller_CreateJobListingRequest,
        __Marshaller_JobListingResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::HireFire.Grpc.GetJobListingsForCompanyRequest, global::HireFire.Grpc.GetJobListingsForCompanyResponse> __Method_GetJobListingsForCompany = new grpc::Method<global::HireFire.Grpc.GetJobListingsForCompanyRequest, global::HireFire.Grpc.GetJobListingsForCompanyResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetJobListingsForCompany",
        __Marshaller_GetJobListingsForCompanyRequest,
        __Marshaller_GetJobListingsForCompanyResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::HireFire.Grpc.GetJobListingsForRecruiterRequest, global::HireFire.Grpc.GetJobListingsForRecruiterResponse> __Method_GetJobListingsForRecruiter = new grpc::Method<global::HireFire.Grpc.GetJobListingsForRecruiterRequest, global::HireFire.Grpc.GetJobListingsForRecruiterResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetJobListingsForRecruiter",
        __Marshaller_GetJobListingsForRecruiterRequest,
        __Marshaller_GetJobListingsForRecruiterResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::HireFire.Grpc.JobReflection.Descriptor.Services[0]; }
    }

    /// <summary>Client for JobListingService</summary>
    public partial class JobListingServiceClient : grpc::ClientBase<JobListingServiceClient>
    {
      /// <summary>Creates a new client for JobListingService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public JobListingServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for JobListingService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public JobListingServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected JobListingServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected JobListingServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::HireFire.Grpc.JobListingResponse CreateJobListing(global::HireFire.Grpc.CreateJobListingRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateJobListing(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::HireFire.Grpc.JobListingResponse CreateJobListing(global::HireFire.Grpc.CreateJobListingRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CreateJobListing, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::HireFire.Grpc.JobListingResponse> CreateJobListingAsync(global::HireFire.Grpc.CreateJobListingRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateJobListingAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::HireFire.Grpc.JobListingResponse> CreateJobListingAsync(global::HireFire.Grpc.CreateJobListingRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CreateJobListing, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::HireFire.Grpc.GetJobListingsForCompanyResponse GetJobListingsForCompany(global::HireFire.Grpc.GetJobListingsForCompanyRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetJobListingsForCompany(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::HireFire.Grpc.GetJobListingsForCompanyResponse GetJobListingsForCompany(global::HireFire.Grpc.GetJobListingsForCompanyRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetJobListingsForCompany, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::HireFire.Grpc.GetJobListingsForCompanyResponse> GetJobListingsForCompanyAsync(global::HireFire.Grpc.GetJobListingsForCompanyRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetJobListingsForCompanyAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::HireFire.Grpc.GetJobListingsForCompanyResponse> GetJobListingsForCompanyAsync(global::HireFire.Grpc.GetJobListingsForCompanyRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetJobListingsForCompany, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::HireFire.Grpc.GetJobListingsForRecruiterResponse GetJobListingsForRecruiter(global::HireFire.Grpc.GetJobListingsForRecruiterRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetJobListingsForRecruiter(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::HireFire.Grpc.GetJobListingsForRecruiterResponse GetJobListingsForRecruiter(global::HireFire.Grpc.GetJobListingsForRecruiterRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetJobListingsForRecruiter, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::HireFire.Grpc.GetJobListingsForRecruiterResponse> GetJobListingsForRecruiterAsync(global::HireFire.Grpc.GetJobListingsForRecruiterRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetJobListingsForRecruiterAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::HireFire.Grpc.GetJobListingsForRecruiterResponse> GetJobListingsForRecruiterAsync(global::HireFire.Grpc.GetJobListingsForRecruiterRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetJobListingsForRecruiter, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override JobListingServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new JobListingServiceClient(configuration);
      }
    }

  }
}
#endregion
